apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      nodeSelector: # Используем nodeSelector для указания, что поды должны быть размещены на нодах с лейблами
        topology.kubernetes.io/zone: zone-1
        topology.kubernetes.io/zone: zone-2
        topology.kubernetes.io/zone: zone-3
      containers:
      - name: my-app-container
        image: my-app-image:latest
        lifecycle:
          preStop:
          exec:
            command: ["/bin/sh", "-c", "sleep 10"]
        volumeMounts: # Монтируем хранилище
        - name: storage-volume
          mountPath: /path/to/mount
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.1"
          limits:
            memory: "128Mi"
            cpu: "0.7"
volumes:
  - name: storage-volume
    persistentVolumeClaim:
      claimName: my-pvc
---
apiVersion: autoscaling/v2 # Используем автоскейлер для автомасштабирования, основываясь на метриках CPU и памяти
kind: HorizontalPodAutoscaler
metadata:
  name: my-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 50
  minReplicas: 4
  maxReplicas: 10
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  # Указываем тип сервиса, который поддерживает мультизональность
  type: LoadBalancer
  loadBalancerIP: ""
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  externalTrafficPolicy: Cluster
---
apiVersion: apps/v1
kind: StatefulSet # Если требуется уникальный идентификатор
metadata:
  name: my-app-statefulset
  labels:
    app: my-app
spec:
  serviceName: "my-app"
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: zone-1
        topology.kubernetes.io/zone: zone-2
        topology.kubernetes.io/zone: zone-3
      containers:
      - name: my-app-container
        image: my-app-image:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.1"
          limits:
            memory: "128Mi"
            cpu: "0.1"
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
